.TH watchteleboy "1" "2015 July 10" "GNU2"
.SH NAME
watchteleboy \- Watch and record IPTV from Teleboy
.SH SYNOPSYS
.B watchteleboy
[
.B --record
]
.br
.B watchteleboy
[
.B --help
|
.B --list
|
.B --version
]
.br
.B watchteleboy
[ options ]
.B --record --channel
.I CHANNEL
[
.B --endtime
.I TIME
|
.B --duration
.I DURATION
[
.B --starttime
.I TIME
]]
.SH DESCRIPTION
.B watchteleboy
plays and records live HDTV streams.
.PP
The new Python version of
.B watchteleboy
does not yet come with an interactive interface. All parameters are required to be given
either through command line arguments or configuration options. Use
.I -h
to show a summary of all available command line options. There are basically three modes of
operation: Playback of live or up to three hours old streams, recording of live or up to three
hour old streams, schedule a future recording as a crontjob.
.PP
The first time
.B watchteleboy
is started, it creates a configuration file in $HOME/.watchteleboy/config. It
then asks you for a valid Teleboy login.
.br
.SH GENERAL OPTIONS
.IP "\fB\-c, \-\-channel CHANNEL"
Specify the channel to be played or recorded.
.br
Use the option
.I --list
to get a list of available channels.
.IP "\fB\-d, \-\-duration DURATION"
Specify the duration in the format
.I [[HH:]MM:]SS
of the show to be watched or recorded. Alternatively,
you can define \fI--endtime\fR.
.IP "\fB\-e, \-\-endtime DATETIME"
Specify an end time for a show to be watched or recorded.
.I DATETIME
is expected to have the format \fI[YYYY-mm-dd] HH:MM[:SS]\fR.
For the date part, also the words \fIyesterday\fR, \fItoday\fR, \fItomorrow\fR are understood.
.IP "\fB\-h, \-\-help"
Print a summary of available options and exit.
.IP "\fB\-l, \-\-list"
Print a list of available channels and exit.
.IP "\fB\-q, \-\-quiet"
Suppress any output during normal operation.
.IP "\fB\-t, \-\-starttime DATETIME"
Specify the start time of the show to be watched or recorded. \fIDATETIME\fR is expected to be of
the format \fI[YYYY-mm-dd] HH:MM[:SS]\fR. In watching mode, any time from a few hours in the past until now is
supported, in recording mode any time from a few hours in the past to anytime in the future. The amount of
"a few hours" was found to be three hours, which is dependent on how long stream segments are cached on CDN
servers. This amount might change anytime. In recording mode, a start time in the future triggers an entry
in the user's crontab.
.IP "\fB\-v, \-\-version"
Print the version of this software and exit.
.SH WATCHING OPTIONS
.IP "\fB\-\-player-opts OPTIONS"
Options passed to player software. Make sure to use an equal sign between command line option and value. Otherwise
.B watchteleboy
will try to parse the value as option because of the leading dashes. EXAMPLE: \fI--player-opts='--keep-open'\fR.
.B watchteleboy
currently only supports \fImpv\fR as player. \fIOPTIONS\fR are passed as command line arguments to \fImpv\fR. Note that
some hard-coded options are passed for playback to work correctly, so conflicting options might be overriden by options
used by the script. \fIOPTIONS\fR also override the configuration parameter \fImpv_opts\fR.
.SH RECORDING OPTIONS
The following options can only be used in recording mode, which is set with the
.I --record
flag.
In recording mode,
.B watchteleboy
writes the received stream to a local file. If not the specified the filename
is composed of the channel name and the current date and time using the format:
.PP
\fBCHANNEL\fR-\fBYYYYmmddHHMMSS.mkv\fR
.PP
The resulting file is a matroska container with a H.264 video stream and an AAC audio stream.
.IP "\fB\-n, \-\-showname NAME"
Specify a filename prefix that is used instead of the channel name.
.IP "\fB\-p, \-\-path DIRECTORY"
Specify directory where recorded shows are saved.
.IP "\fB\-r, \-\-record"
Record a stream instead of watching it.
.SH CONFIGURATION FILE
.B watchteleboy
reads parameters from its configuration file, which is located
in \fI$HOME/.watchteleboy/config\fR. Some of those parameters may be overriden by options specified on the
command line.
.PP
.I PARAMETERS:
.RS
.B teleboy_user
.RS
Teleboy account the script uses to login to the service.
.RE
.B teleboy_pass
.RS
Password used to log in to Teleboy.
.RE
.B channel_selection
.RS
Sets the type of channel list to be used. Allowed values are 'all', 'custom'. 'all'
shows all available channels in default order, 'custom' shows user-selected channels
in user-selected order. The selection and order can be configured by visiting:
http://www.teleboy.ch/en/sender
.RE
.B mpv_opts
.RS
Options passed to mpv. Those options are overriden by the commandline option \fI--player-opts\fR.
.RE
.B record_dir
.RS
Directory where recorded streams are saved.
.RE
.B max_bitrate
.RS
Defines which adaptation set is used for downloading the stream. Usually, several video qualities
with different resolutions and bandwidths are available per stream. \fBwatchteleboy\fR tries to find
the best-quality adaption set that still fits the given \fImax_bitrate\fR.
.RS
.SH EXAMPLES
.B Schedule a recording:
.RS
.PP
watchteleboy --record --channel Arte --starttime '2038-01-19 23:15' --endtime '2038-01-20 00:50'
.PP
.RE
.B Record for an hour from now:
.RS
.PP
watchteleboy --record --channel Arte --duration 1:00:00
.PP
.RE
.B Record from now until tonight at 23:15:
.RS
.PP
watchteleboy --record --channel Arte --endtime 23:15
.PP
.RE
.B Watch 'Tatort' when the children finally are asleep:
.RS
.PP
watchteleboy -c ARD -t 20:15 -e 21:50
.PP
.RE
.SH "BUGS"
Report bugs and feature requests to https://github.com/reduzent/watchteleboy
.SH AUTHOR
Roman Haefeli <reduzent@gmail.com>
.SH SEE ALSO
.BR mpv (1),
.BR crontab (1)

