#!/usr/bin/env python3

import sys
import datetime
from wt_classes import WatchTeleboyError, WatchTeleboySession, WatchTeleboyPlayer
from wt_helpers import create_env, parse_time_string, schedule_recording


def main():
    defaults = {
        'wt_version': '2.0',
        'wt_dir': '{home_dir}/.watchteleboy',
        'configfile': '{wt_dir}/config',
        'session_cache': '{wt_dir}/session_cache',
        'mpv_opts': '--keep-open',
        'channel_selection': 'all',
        'record_dir': '{wt_dir}',
        'max_bitrate': '4800000',
        'fifo': '{wt_dir}/fifo_{wt_instance}_{content_type}_{id}',
        'mpv': '/usr/bin/mpv',
        'mpv_args': [
            '--keep-open',
            '--force-seekable=yes',
            '--cache=yes',
            '--cache-secs=600',
            '--demuxer-max-bytes=1GiB',
        ]
    }
    env = create_env(defaults)
    if env['version']:
        print(f'watchteleboy {env["wt_version"]}')
        sys.exit(0)
    wts = WatchTeleboySession(env['session_cache'])
    if not wts.logged_in():
        try:
            assert wts.login(user=env['teleboy_user'], password=env['teleboy_pass'])
        except AssertionError:
            sys.exit(1)
    wts.set_channel_selection(env['channel_selection'])
    if env['list']:
        wts.list_channels()
        sys.exit(0)
    ch = env['channel'] if env['channel'] else 'SRF1'
    ch, mpd_url = wts.get_stream_url(ch) # also returns canonical channel name
    if env['print_url']:
        print(mpd_url)
        sys.exit(0)
    try:
        if env['record'] and env['starttime']:
            st_obj = parse_time_string(env['starttime'])
            if st_obj > datetime.datetime.now() + datetime.timedelta(seconds=10):
                schedule_recording(env)
                sys.exit()
    except WatchTeleboyError:
        sys.exit(1)
    player = WatchTeleboyPlayer(env)
    try:
        player.set_mpd_url(mpd_url, ch)
    except WatchTeleboyError:
        sys.exit(1)
    if env['record']:
        try:
            player.record()
            player.wait()
        except WatchTeleboyError:
            sys.exit(1)
    else:
        try:
            player.play()
            player.wait()
        except WatchTeleboyError:
            sys.exit(1)
    sys.exit(0)

if __name__ == '__main__':
    main()

