#!/bin/bash -i
################################################
# Bash script for watching/recording online TV 
# streams from teleboy.ch without browser and 
# =no f*** flash=.
#
# License:  GNU GPL v2
# Author:   Alexander Tuchacek
# written:  2011-05-21
# modified by: Roman Haefeli
# modified on: 2011-09-13
# program version: (check below)
################################################

VERSION=1.3

# Set some default values
TMPDIR=/tmp
UAGENT='Mozilla/5.0 (X11; Linux i686; rv:5.0) Gecko/20100101 Firefox/5.0'
MPLAYEROPTS="-really-quiet"
RECORDPATH=$(pwd)
CHANSELECTION=all

# Check dependencies
programlist="rtmpdump mplayer wget grep cut crontab date recode"
for program in $programlist
do
    if ! which $program > /dev/null
    then
        echo "ERROR:" 1>&2
        echo "Could not find ${program}. Is it installed?" 1>&2
        exit 1
    fi
done

# Read config (overrides default values) or create it
CONFIG=~/.watchteleboyrc
if [ -f $CONFIG ]
then
  . $CONFIG
else
  echo "In order for this script to work properly you need to"
  echo "provide your user credentials for the teleboy.ch"
  echo "service."
  while true
  do
    read -p "Please enter your user name: " USER
    read -s -p "Please enter your password:  " PASS
    echo ""
    read -s -p "Confirm your password:       " PASS2
    echo "" 
    if [ "$PASS" == "$PASS2" ]
    then
      break
    else
      echo "The password entries don't match."
    fi
  done  
  echo "CAUTION: writing plain text password to the config file!"
  echo "USER='$USER'" >> $CONFIG
  echo "PASS='$PASS'" >> $CONFIG
  echo "created config file $CONFIG"  
fi

# check availability of login
# since teleboy.ch only allows you to stream one channel per session, 
# we use a different login for each session (if available)
# more users can be configured in CONFIG
userinc=1
if [ -f $TMPDIR/watchteleboy.${USER}/loggedin ]
then 
  while true
  do
    ((userinc += 1))
    uservar="USER${userinc}"
    if [ -z "${!uservar}" ]
    then
      echo "Available logins already in use. Exiting" 1>&2 
      echo "You might want to configure more credentials in $CONFIG" 1>&2
      exit 1
    fi
    if ! [ -f $TMPDIR/watchteleboy.${!uservar}/loggedin ]
    then
      break # we found a login not yet in use
    fi
  done
  # use login not yet in use
  USER=${!uservar}
  passvar="PASS${userinc}"
  PASS=${!passvar}
fi

# set working directory for keeping session data
TMPPATH="${TMPDIR}/watchteleboy.${USER}"

# Comandline argument parsing
channel=false
deleteme=false
duration=false
endtime=false
help=false
list=false
path=false
record=false
showname=false
starttime=false
version=false
while [ $# -gt 0 ]
do
  case "$1" in
    -c|--channel) channel=true; CHANNEL=$2; shift;;
    -d|--duration) duration=true; DURATION="$2"; shift;;
    -e|--endtime) endtime=true; ENDTIME="$2"; shift;;
    -h|--help) help=true;;
    -l|--list) list=true;;
    -n|--showname) showname=true; SHOWNAME="$2"; shift;;
    -m|--mplayer-opts) mplayeropts=true; MPLAYEROPTS="$2"; shift;;
    -p|--path) path=true; RECORDPATH="$2"; shift;;
    -r|--record) record=true;;
    -t|--starttime) starttime=true; STARTTIME="$2"; shift;;
    -v|--version) version=true;;
    --deleteme) deleteme=true; DELETEME="$2"; shift;;
    -*) echo "$(basename $0): error - unrecognized option '$1'" 1>&2
        echo "use '$(basename $0) --help' to get a list of available options" 1>&2
        exit 1;;
    *)  break;;
  esac
  shift
done

# option -v|--version
if $version
then
  echo "watchteleboy $VERSION"
  echo "written by Alexander Tuchacek & Roman Haefeli"
  echo "Licensed under the GNU Public License 2.0 (GPL-2)"
  exit
fi

# option -h|--help
if $help
then
  cat << EOF

watchteleboy
------------

  <no options>            go into interactive mode

GENERAL OPTIONS:

  -c|--channel CHANNEL    specify a channel
  -h|--help               show this help and exit
  -l|--list               print a list of all channels and exit
  -v|--version            print the version of this program

OPTIONS FOR RECORDING (require -r|--record):

  -e|--endtime TIME       schedule the end time of the recording
  -d|--duration SECONDS	  specify the duration of the recording
  -n|--showname SHOWNAME  specify file name prefix
  -p|--path DIR		  specify target directory
  -r|--record             record a stream instead of watching it
  -t|--starttime TIME	  schedule the start time for a recording

MPLAYER SPECIFIC OPTIONS:

  -m|--mplayer-opts OPTS  pass options to mplayer

EOF
  exit
fi

function table_format_list {
  list="$1"
  num=$(echo "$list" | wc -l)
  longest=$(for i in $(echo $list); do echo $i | wc -c; done | sort -r -n | head -n 1)
  let "colwidth = $longest + 1"
  paddedlist=$(echo "$list" | sed -e :a -e "s/^.\{1,${colwidth}\}$/& /;ta")
  let "cols = COLUMNS/colwidth-1"
  let "rows = (num/cols)+(1&&(num/cols))"
  let "remaind = num % cols"
  function get_element {
  # $1: index
    if [ $1 -gt 0 ] && [ $1 -le $num ]
    then
      echo -n "$paddedlist" | head -n ${1} | tail -n1
    else
      echo -n ""
    fi
  }
  for row in $(seq $rows)
  do
    rowcontent=""
    for col in $(seq $cols)
    do
      let "index = ((row - 1) * cols) + col"
      rowcontent="${rowcontent}$(get_element $index)"
    done
    echo "$rowcontent"
  done
}

# Check record path validity
if $record
then
  if [ ! -d "$RECORDPATH" ]
  then
    echo "There is no such directory: $RECORDPATH" 1>&2
    exit 1
  elif [ ! -w "$RECORDPATH" ]
  then
    echo "You don't have permission to write to $RECORDPATH" 1>&2
    exit 1
  fi
fi

# Create TMPDIR if required
if  [ ! -d $TMPPATH ]
then
  if ! mkdir -p $TMPPATH
  then
    echo "Could not create directory: $TMPPATH" 1>&2
    exit 1
  fi
fi

# get the session cookie
echo -n "login (as '$USER')..."
POST="login=${USER}&password=${PASS}&x=13&y=17&followup=%2Ftv%2Fplayer%2Fplayer.php"
URL="http://www.teleboy.ch/layer/rectv/free_live_tv.inc.php"
COOKIE=$(wget -U "$UAGENT" \
  --quiet \
  --no-check-certificate \
  --save-cookies /dev/stdout \
  --keep-session-cookies \
  --post-data $POST \
  -O $TMPPATH/step1.html \
  $URL)

# remove loggedin file on exit
function cleanup {
  rm -rf $TMPPATH
  echo ""
}

# check if login was succesful
cat $TMPPATH/step1.html | grep "Falsche Eingaben" > /dev/null || \
cat $TMPPATH/step1.html | grep "<h1>Login f&uuml;r Member</h1>" > /dev/null
if [ $? -eq 0 ]
then
  echo "failed!!!!" 1>&2
  echo "Please check your credentials in the config file:" 1>&2
  echo "$CONFIG" 1>&2
  exit 1
else
  echo "ok"
  touch $TMPPATH/loggedin
  trap cleanup INT TERM EXIT
fi

# get the station / channel list
echo -n "receive channel list..."
POST="cmd=getStations&category=${CHANSELECTION}"
URL="http://www.teleboy.ch/tv/player/includes/ajax.php"
wget --user-agent "$UAGENT" \
    --quiet \
    --load-cookies <(echo "$COOKIE") \
    --post-data $POST \
    --output-document $TMPPATH/step2.html.latin1 \
    $URL
iconv -f LATIN1 -t UTF-8 $TMPPATH/step2.html.latin1 > $TMPPATH/step2.html
channelnames=$(grep -e " <img.*src=\"/img/station/.*/logo" $TMPPATH/step2.html | cut -d'"' -f8)
channelids=$(grep "javascript:getLiveChannelData" $TMPPATH/step2.html | cut -d "(" -f 2 | cut -d ")" -f1 | sed -e 's/,//g')
CHANNELS=$(paste -d' ' \
  <(echo "$channelnames" | \
    sed -e '
      s/ //g
      s/\.//g
      s/+/plus/g
      s/Ô/O/g
    ' | head -n $(echo "$channelids" | wc -l)) \
  <(echo "$channelids"))
echo "done"
CHANNELS="
$(echo "$CHANNELS" | grep -iv euronews)
SF1_o 159 0
SFzwei_o 108 0
Arte_fr 161 20
EuroNews_de 216 0
EuroNews_fr 158 0
EuroNews_it 217 0
EuroNews_en 45 0
"

# option -l|--list
if $list
then
  echo "$CHANNELS" | cut -d " " -f 1 
  exit
fi

# get flashplayer url
SWFFILE=$(wget \
  -O - \
  --quiet \
  "http://www.teleboy.ch/tv/player/player.php" | \
  grep "nelloplayer" | \
  cut -d'"' -f2 | \
  tail -n1)

# Da Time Valeditee Checkah
function check_time_validity {
  # ARGS:
  # 1: datetime string
  if ! date -d "$1" > /dev/null
  then
    echo "Could not understand time format." 1>&2
    exit 1
  fi
}

function compose_rtmp_command {
  # ARGS:
  # 1: channel
  # 2: output file
  cid=$(echo "$CHANNELS" | grep -i "^${1} " | cut -d" " -f2)
  cid2=$(echo "$CHANNELS" | grep -i "^${1} " | cut -d" " -f3)
  URLBASE="http://www.teleboy.ch/tv/player"
  POST="cmd=getLiveChannelParams&cid=${cid}&cid2=${cid2}"
  STREAMINFO=$(wget -U "$UAGENT" \
    --quiet \
    --referer "${URLBASE}/player.php" \
    --load-cookies <(echo "$COOKIE") \
    --post-data $POST \
    --keep-session-cookies \
    --output-document /dev/stdout \
    "${URLBASE}/includes/ajax.php")

  # get rtmp parameters
  x11=$(echo "$STREAMINFO" | cut -d "|" -f11)
  c1=$(echo "$STREAMINFO"  | cut -d "|" -f4)
  c2=$(echo "$STREAMINFO"  | cut -d "|" -f5)
  c3=$(echo "$STREAMINFO"  | cut -d "|" -f6)
  c4=$(echo "$STREAMINFO"  | cut -d "|" -f7)
  c5=$(echo "$STREAMINFO"  | cut -d "|" -f8)
  c6=$(echo "$STREAMINFO"  | cut -d "|" -f9)
  gip=$(echo "$STREAMINFO"  | cut -d "|" -f10)
  playpath=${cid}${c2}.stream

  # LOESCHI / show channel name
  echo "$STREAMINFO"  | cut -d "|" -f2
  
  # get IP address of streaming server
  GIPURL="${URLBASE}/includes/getserver.php?version=${gip}&nocache=1314619521398"
  wget -U "$UAGENT" \
    --quiet \
    -O $TMPPATH/step4.html \
    $GIPURL
  IP=$(cat $TMPPATH/step4.html | cut -d "=" -f2)

  # rtmpdump command
  RTMP="rtmpdump 
    -r rtmp://${IP}/${x11} 
    -a ${x11}
    -f LNX 10,3,183,7 
    -W ${URLBASE}/${SWFFILE} 
    -p ${URLBASE}/player.php 
    -y $playpath
    -C S:$c1 -C S:$c2 -C S:$c3 -C S:$c4 -C S:$c5
    -q 
    -o $2 "
}

# test channel input validity
function chan_validity {
  # ARGS:
  # 1: channel
  if [ -z "$CHANNEL" ]
  then
    echo "Please specify a channel"
    return 1
  elif echo $CHANNELS | grep -i $1 > /dev/null
  then
    return 0
  else
    echo "'$CHANNEL' is not a valid channel." 1>&2
    echo "Use '--list' to display available channels." 1>&2
    return 1
  fi
}

# channel selector
function chan_selectah {
  while true
  do
    echo -e "\nAVAILABLE CHANNELS ($CHANSELECTION):"
    chanlist=$(echo "$CHANNELS" | cut -d " " -f 1)
    table_format_list "$chanlist"
    read -p "Select TV Channel: " -e SEL
    if [ -n "$SEL" ]
    then
      echo $CHANNELS | grep -i $SEL > /dev/null && \
        CHANNEL="$SEL" && \
        break
      echo "Channel '$SEL' is not available..." 
      sleep 1
    fi
  done 
}

function require_r_opt {
  # ARGS:
  # 1: option name
  if $record
  then
    return 0
  else
    echo "The option '--${1}' requires the '--record' option" 1>&2
    exit 1
  fi
}

# option -t|--starttime
crontempfile="${TMPPATH}/crontab.tmp"
if $starttime
then
  require_r_opt "starttime"
  if $endtime || $duration
  then
    check_time_validity "$STARTTIME"
    starttimeepoch=$(date -d "$STARTTIME" +%s)
    if [ $starttimeepoch -lt $(date +%s) ]
    then
      echo "The specified start time is already over." 1>&2
      exit 1
    fi
    if $endtime
    then
      check_time_validity "$ENDTIME"
      endtimeepoch=$(date -d "$ENDTIME" +%s)
      if [ $endtimeepoch -lt $starttimeepoch ]
      then
        echo "The specified end time is before the start time." 1>&2
        exit 1
      fi
      let DURATION=$endtimeepoch-$starttimeepoch
    elif $duration
    then
      if ! [ "$DURATION" -ge 0 ] 2>&-
      then
        echo "The specified duration '$DURATION' is not a number." 1>&2
        exit 1
      fi
    fi
    if $channel
    then
      chan_validity $CHANNEL || exit 1
    else
      echo "You need to specify a channel with '--channel'" 1>&2
      exit 1
    fi
    # Now we have validated all required parameters
    echo "Scheduled for recording:"
    echo -e "Start time:\t$(date -d "$STARTTIME" "+%a, %F %H:%M")"
    $endtime && echo -e "End time:\t$(date -d "$ENDTIME" "+%a, %F %H:%M")"
    $duration && echo -e "Duration:\t${DURATION} sec"
    echo -e "Channel:\t$CHANNEL"
    echo -e "Directory:\t$RECORDPATH"
    $showname && echo -e "Show:\t\t$SHOWNAME"
    read -p "Are those settings correct? (Y/n) "
    if [ "$REPLY" == "n" ]
    then
      echo "Cancelled by user. Quit." 1>&2
      exit 1
    fi
    crontab -l > /dev/null 2>&1 && crontab -l > $crontempfile || touch $crontempfile
    echo -ne "$(date -d "$STARTTIME" +"%M %H %d %m") *\t${0} --record " >> $crontempfile
    echo -ne "--channel ${CHANNEL} --duration ${DURATION} " >> $crontempfile
    echo -ne "--deleteme ${RANDOM}${RANDOM} " >> $crontempfile
    $showname && echo -ne "--showname '${SHOWNAME}' " >> $crontempfile
    echo -ne "--path ${RECORDPATH}\n" >> $crontempfile
    crontab < $crontempfile
    rm $crontempfile
    echo "Done."
    exit 0
  else 
    echo "You must specify either --duration or --endtime" 1>&2
    exit 1
  fi
fi

# option --deleteme
if $deleteme
then
  crontab -l > $crontempfile
  sed -i "/$DELETEME/ d" $crontempfile
  crontab < $crontempfile
  rm $crontempfile
fi

# Compose mplayer command
MPLAYER="mplayer $MPLAYEROPTS - "

# Compose rmtpdump output filename
function compose_outfile {
  # ARGS:
  # 1: Channel
  if $record
  then
    if $showname
    then
      OUTFILE=${RECORDPATH}/${SHOWNAME}-$(date +%Y%m%d%H%M).flv
    else
      OUTFILE=${RECORDPATH}/${1}-$(date +%Y%m%d%H%M).flv
    fi
  else
    OUTFILE="-"
  fi
} 

function player_recorder {
  # ARGS:
  # 1: Channel
  compose_outfile $1
  compose_rtmp_command $1 $OUTFILE
  if $record
  then
    $RTMP &
    PID=$!
  else
    $RTMP | $MPLAYER 2> /dev/null
  fi
}

# Da Keestroke Waitah
function  wait_s_key {
  echo "Press the 's' key to stop the recording." 
  keypress=""
  while [ "$keypress" != "s" ]
  do
    read -s -n1  keypress
  done
}

# option -e|--endtime
if $endtime && ! $duration
then
  require_r_opt "endtime"
  check_time_validity "$ENDTIME"
  endtimeepoch=$(date -d "$ENDTIME" +%s)
  nowepoch=$(date +%s)
  if [ $endtimeepoch -lt $nowepoch ]
  then
    echo "The specified end time is already over." 1>&2
    exit 1
  fi
  let DURATION=${endtimeepoch}-${nowepoch}
  duration=true
fi

# option -d|--duration
if $duration
then
  require_r_opt "duration"
  if ! [ "$DURATION" -ge 0 ] 2>&-
  then
    echo "The specified duration '$DURATION' is not a number." 1>&2
    exit 1
  fi
  chan_validity $CHANNEL || exit 1
  player_recorder $CHANNEL
  echo "Now recording $CHANNEL for $DURATION seconds."
  sleep $DURATION
  kill $PID
  echo "Stopped recording."
  exit 0
fi

# option -c|--channel
if $channel
then
  if chan_validity $CHANNEL
  then
    if $record
    then
      echo "Now recording:"
      player_recorder $CHANNEL
      wait_s_key
      kill $PID
      echo "Stopped recording."
      exit 0
    else
      echo "Now playing:"
      player_recorder $CHANNEL
    fi
    exit 0
  else
    echo "Channel '$CHANNEL' is not available..." 1>&2
    exit 1
  fi
fi

# Loop for interactive mode
while true
do
  chan_selectah
  if $record
  then
    player_recorder $CHANNEL
    echo "Now recording:"
    wait_s_key
    kill $PID
    echo "Stopped recording."
  else
    echo "Now playing:"
    player_recorder $CHANNEL
  fi
done

exit 0

